country = ['japan','italy','spain','france','egypt']
print(country)
print(sorted(country))
print(country)
print(sorted(country))
print(country)
country.sort(reverse=True)
print(country)
country.sort(reverse=True)
print(country)
country.sort()
print(country)
country.sort(reverse=True)
print(country)